name: Start AWS cloud server

on:
  workflow_call:
jobs:
  demo:
    name: demo
    runs-on: ubuntu-latest
    env:
     INSTANCE_ID: ${{ secrets.INSTANCE_ID }}
    steps:
      - name: demo
        run: echo $INSTANCE_ID
