name: Stop AWS cloud server

on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  start-server:
    name: Stop OpenVPN Server
    runs-on: ubuntu-latest
    env:
      INSTANCE_ID: ${{ secrets.INSTANCE_ID }}
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: ap-south-1
       
      - name: Stop EC2 instance
        run: |
          aws ec2 stop-instances --instance-ids $INSTANCE_ID
          sleep 20
